Box2DBody = PropertySupport()

Box2DBody:setPropertyName("x")
Box2DBody:setPropertyName("y")
Box2DBody:setPropertyName("rotation")
Box2DBody:setPropertyName("awake")
Box2DBody:setPropertyName("active")
Box2DBody:setPropertyName("bullet")
Box2DBody:setPropertyName("fixedRotation")
Box2DBody:setPropertyName("angularVelocity")
Box2DBody:setPropertyName("angularDamping")
Box2DBody:setPropertyName("linearVelocityX")
Box2DBody:setPropertyName("linearVelocityY")
Box2DBody:setPropertyName("linearDamping")
Box2DBody:setPropertyName("isSensor")
Box2DBody:setPropertyName("isSleepingAllowed")
Box2DBody:setPropertyName("bodyType")
